import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)

// PWA: the service worker + manifest are now generated by vite-plugin-pwa
// (see vite.config.js). Registration is injected automatically at build
// time, so no manual navigator.serviceWorker.register here.
